# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiInferenceStub(object):
    """========== 服务定义 ==========

    推理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPredict = channel.stream_stream(
                '/cy.llm.AiInference/StreamPredict',
                request_serializer=ai__service__pb2.StreamPredictRequest.SerializeToString,
                response_deserializer=ai__service__pb2.StreamPredictResponse.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/cy.llm.AiInference/Control',
                request_serializer=ai__service__pb2.ControlMessage.SerializeToString,
                response_deserializer=ai__service__pb2.ControlMessage.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cy.llm.AiInference/Health',
                request_serializer=ai__service__pb2.WorkerHealthRequest.SerializeToString,
                response_deserializer=ai__service__pb2.WorkerHealthResponse.FromString,
                _registered_method=True)


class AiInferenceServicer(object):
    """========== 服务定义 ==========

    推理服务
    """

    def StreamPredict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=ai__service__pb2.StreamPredictRequest.FromString,
                    response_serializer=ai__service__pb2.StreamPredictResponse.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=ai__service__pb2.ControlMessage.FromString,
                    response_serializer=ai__service__pb2.ControlMessage.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__service__pb2.WorkerHealthRequest.FromString,
                    response_serializer=ai__service__pb2.WorkerHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cy.llm.AiInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cy.llm.AiInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiInference(object):
    """========== 服务定义 ==========

    推理服务
    """

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cy.llm.AiInference/StreamPredict',
            ai__service__pb2.StreamPredictRequest.SerializeToString,
            ai__service__pb2.StreamPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiInference/Control',
            ai__service__pb2.ControlMessage.SerializeToString,
            ai__service__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiInference/Health',
            ai__service__pb2.WorkerHealthRequest.SerializeToString,
            ai__service__pb2.WorkerHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AiTrainingStub(object):
    """训练服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTraining = channel.unary_stream(
                '/cy.llm.AiTraining/StartTraining',
                request_serializer=ai__service__pb2.TrainingRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TrainingProgress.FromString,
                _registered_method=True)
        self.GetTrainingStatus = channel.unary_unary(
                '/cy.llm.AiTraining/GetTrainingStatus',
                request_serializer=ai__service__pb2.TrainingStatusRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TrainingStatusResponse.FromString,
                _registered_method=True)
        self.CancelTraining = channel.unary_unary(
                '/cy.llm.AiTraining/CancelTraining',
                request_serializer=ai__service__pb2.CancelTrainingRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CancelTrainingResponse.FromString,
                _registered_method=True)
        self.ListTrainingJobs = channel.unary_unary(
                '/cy.llm.AiTraining/ListTrainingJobs',
                request_serializer=ai__service__pb2.ListTrainingJobsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ListTrainingJobsResponse.FromString,
                _registered_method=True)
        self.ExecuteCustomScript = channel.unary_stream(
                '/cy.llm.AiTraining/ExecuteCustomScript',
                request_serializer=ai__service__pb2.CustomScriptExecutionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CustomScriptExecutionProgress.FromString,
                _registered_method=True)
        self.CancelCustomScript = channel.unary_unary(
                '/cy.llm.AiTraining/CancelCustomScript',
                request_serializer=ai__service__pb2.CancelCustomScriptRequest.SerializeToString,
                response_deserializer=ai__service__pb2.CancelCustomScriptResponse.FromString,
                _registered_method=True)


class AiTrainingServicer(object):
    """训练服务
    """

    def StartTraining(self, request, context):
        """启动训练任务，流式返回进度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStatus(self, request, context):
        """查询训练状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTraining(self, request, context):
        """取消训练任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrainingJobs(self, request, context):
        """列出训练任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCustomScript(self, request, context):
        """自定义脚本执行
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelCustomScript(self, request, context):
        """取消自定义脚本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiTrainingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTraining': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=ai__service__pb2.TrainingRequest.FromString,
                    response_serializer=ai__service__pb2.TrainingProgress.SerializeToString,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=ai__service__pb2.TrainingStatusRequest.FromString,
                    response_serializer=ai__service__pb2.TrainingStatusResponse.SerializeToString,
            ),
            'CancelTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTraining,
                    request_deserializer=ai__service__pb2.CancelTrainingRequest.FromString,
                    response_serializer=ai__service__pb2.CancelTrainingResponse.SerializeToString,
            ),
            'ListTrainingJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrainingJobs,
                    request_deserializer=ai__service__pb2.ListTrainingJobsRequest.FromString,
                    response_serializer=ai__service__pb2.ListTrainingJobsResponse.SerializeToString,
            ),
            'ExecuteCustomScript': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCustomScript,
                    request_deserializer=ai__service__pb2.CustomScriptExecutionRequest.FromString,
                    response_serializer=ai__service__pb2.CustomScriptExecutionProgress.SerializeToString,
            ),
            'CancelCustomScript': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelCustomScript,
                    request_deserializer=ai__service__pb2.CancelCustomScriptRequest.FromString,
                    response_serializer=ai__service__pb2.CancelCustomScriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cy.llm.AiTraining', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cy.llm.AiTraining', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiTraining(object):
    """训练服务
    """

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cy.llm.AiTraining/StartTraining',
            ai__service__pb2.TrainingRequest.SerializeToString,
            ai__service__pb2.TrainingProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiTraining/GetTrainingStatus',
            ai__service__pb2.TrainingStatusRequest.SerializeToString,
            ai__service__pb2.TrainingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiTraining/CancelTraining',
            ai__service__pb2.CancelTrainingRequest.SerializeToString,
            ai__service__pb2.CancelTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrainingJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiTraining/ListTrainingJobs',
            ai__service__pb2.ListTrainingJobsRequest.SerializeToString,
            ai__service__pb2.ListTrainingJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCustomScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cy.llm.AiTraining/ExecuteCustomScript',
            ai__service__pb2.CustomScriptExecutionRequest.SerializeToString,
            ai__service__pb2.CustomScriptExecutionProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelCustomScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiTraining/CancelCustomScript',
            ai__service__pb2.CancelCustomScriptRequest.SerializeToString,
            ai__service__pb2.CancelCustomScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
